### ISSUE TITLE
No attribution

### ISSUE THREAD

**Issue by tobyjaffey** [semiotproject/minicoap#1]
This project is derived from microcoap, as can be seen from the sources, but you do not acknowledge it anywhere and have removed my name from the license file.

https://github.com/1248/microcoap/blob/master/LICENSE.txt

**Comment by a-andreyev** [comment]
Hello, @tobyjaffey! I'm really sorry, there is no malicious intent -- it was my mistake.
I've mentioned my project [here](https://github.com/1248/microcoap/issues/4#issuecomment-220824062), but selected available MIT licence at github.
I'm going to change the licence file right now, feel free to correct me more, minicoap is based on microcoap for about 99%
